import type { Product, MarketMatch, Channel, ActivityItem, Artisan } from './types';

export const artisan: Artisan = {
  name: 'Ramesh Kumar',
  craft: 'Blue Pottery',
  village: 'Khurja',
  state: 'Uttar Pradesh',
  rating: 4.8,
  totalProducts: 24,
  totalSales: 156,
  monthlyEarnings: 28400,
  growth: 23,
};

export const products: Product[] = [
  {
    id: 'p1',
    name: 'Hand-painted Blue Ceramic Vase',
    category: 'Pottery',
    image: 'https://images.pexels.com/photos/18646120/pexels-photo-18646120.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    price: 1200,
    suggestedPrice: 1450,
    status: 'listed',
    languages: ['English', 'Hindi', 'Tamil'],
    markets: 3,
    views: 248,
    createdAt: '2026-08-28',
  },
  {
    id: 'p2',
    name: 'Traditional Brass Earrings',
    category: 'Jewellery',
    image: 'https://images.pexels.com/photos/15955332/pexels-photo-15955332.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    price: 850,
    suggestedPrice: 920,
    status: 'published',
    languages: ['English', 'Hindi', 'Bengali', 'Telugu'],
    markets: 5,
    views: 412,
    createdAt: '2026-08-25',
  },
  {
    id: 'p3',
    name: 'Handwoven Cotton Saree',
    category: 'Textiles',
    image: 'https://images.pexels.com/photos/34131689/pexels-photo-34131689.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    price: 2400,
    suggestedPrice: 2650,
    status: 'listed',
    languages: ['English', 'Hindi'],
    markets: 2,
    views: 186,
    createdAt: '2026-08-30',
  },
  {
    id: 'p4',
    name: 'Moroccan-style Decorative Plate',
    category: 'Pottery',
    image: 'https://images.pexels.com/photos/18646111/pexels-photo-18646111.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    price: 680,
    suggestedPrice: 750,
    status: 'draft',
    languages: ['English'],
    markets: 0,
    views: 0,
    createdAt: '2026-09-01',
  },
  {
    id: 'p5',
    name: 'Gemstone Gold Ring',
    category: 'Jewellery',
    image: 'https://images.pexels.com/photos/32382389/pexels-photo-32382389.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    price: 3200,
    suggestedPrice: 3500,
    status: 'published',
    languages: ['English', 'Hindi', 'Marathi', 'Kannada'],
    markets: 7,
    views: 689,
    createdAt: '2026-08-20',
  },
  {
    id: 'p6',
    name: 'Geometric Pattern Rug',
    category: 'Home Decor',
    image: 'https://images.pexels.com/photos/31854096/pexels-photo-31854096.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    price: 4500,
    suggestedPrice: 4800,
    status: 'listed',
    languages: ['English', 'Hindi', 'Gujarati'],
    markets: 4,
    views: 321,
    createdAt: '2026-08-27',
  },
];

export const marketMatches: MarketMatch[] = [
  {
    id: 'm1',
    name: 'Dilli Haat, New Delhi',
    type: 'Government Craft Market',
    location: 'New Delhi',
    matchScore: 94,
    demand: 'high',
    avgPrice: 1400,
    buyers: 320,
  },
  {
    id: 'm2',
    name: 'Urban Artisan Store, Mumbai',
    type: 'Retail Chain',
    location: 'Mumbai, Maharashtra',
    matchScore: 88,
    demand: 'high',
    avgPrice: 1600,
    buyers: 180,
  },
  {
    id: 'm3',
    name: 'Crafts Council of India Expo',
    type: 'Exhibition',
    location: 'Chennai, Tamil Nadu',
    matchScore: 82,
    demand: 'medium',
    avgPrice: 1300,
    buyers: 95,
  },
  {
    id: 'm4',
    name: 'Tribes India Online',
    type: 'Government E-commerce',
    location: 'Pan-India',
    matchScore: 79,
    demand: 'medium',
    avgPrice: 1100,
    buyers: 540,
  },
  {
    id: 'm5',
    name: 'Local Handicraft Cooperative',
    type: 'Cooperative',
    location: 'Khurja, Uttar Pradesh',
    matchScore: 71,
    demand: 'low',
    avgPrice: 900,
    buyers: 42,
  },
];

export const channels: Channel[] = [
  { id: 'c1', name: 'Amazon Karigar', icon: 'shopping-bag', connected: true, products: 12, views: 1840 },
  { id: 'c2', name: 'Flipkart Samarth', icon: 'package', connected: true, products: 8, views: 920 },
  { id: 'c3', name: 'Meesho', icon: 'smartphone', connected: true, products: 15, views: 2100 },
  { id: 'c4', name: 'WhatsApp Catalog', icon: 'message-circle', connected: false, products: 0, views: 0 },
  { id: 'c5', name: 'Instagram Shop', icon: 'instagram', connected: false, products: 0, views: 0 },
  { id: 'c6', name: 'Government e-Marketplace', icon: 'landmark', connected: true, products: 6, views: 340 },
];

export const recentActivity: ActivityItem[] = [
  { id: 'a1', type: 'photo', title: 'Product photos enhanced', description: 'Blue Ceramic Vase — 3 photos cleaned up', time: '2 hours ago' },
  { id: 'a2', type: 'price', title: 'Price suggestion accepted', description: 'Brass Earrings price set to ₹850', time: '5 hours ago' },
  { id: 'a3', type: 'voice', title: 'Voice catalogue created', description: 'Geometric Pattern Rug described in Hindi', time: 'Yesterday' },
  { id: 'a4', type: 'market', title: 'New market match found', description: 'Dilli Haat — 94% match for your pottery', time: 'Yesterday' },
  { id: 'a5', type: 'publish', title: 'Published to 3 channels', description: 'Gemstone Gold Ring now live on Meesho, Amazon, Flipkart', time: '2 days ago' },
  { id: 'a6', type: 'view', title: 'Product trending', description: 'Gemstone Gold Ring got 89 new views', time: '2 days ago' },
];
