import type { Product, Bid, Artisan, ChatMessage, ProductInsight } from './types';

export const artisan: Artisan = {
  name: 'Ramesh Kumar',
  craft: 'Blue Pottery',
  village: 'Khurja',
  state: 'Uttar Pradesh',
  rating: 4.8,
  totalProducts: 24,
  totalSales: 156,
  monthlyEarnings: 28400,
  growth: 23,
};

export const products: Product[] = [
  {
    id: 'p1',
    name: 'Hand-painted Blue Ceramic Vase',
    category: 'Pottery',
    image: 'https://images.pexels.com/photos/18646120/pexels-photo-18646120.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    price: 1200,
    suggestedPrice: 1450,
    status: 'listed',
    languages: ['English', 'Hindi', 'Tamil'],
    markets: 3,
    views: 248,
    createdAt: '2026-08-28',
  },
  {
    id: 'p2',
    name: 'Traditional Brass Earrings',
    category: 'Jewellery',
    image: 'https://images.pexels.com/photos/15955332/pexels-photo-15955332.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    price: 850,
    suggestedPrice: 920,
    status: 'published',
    languages: ['English', 'Hindi', 'Bengali', 'Telugu'],
    markets: 5,
    views: 412,
    createdAt: '2026-08-25',
  },
  {
    id: 'p3',
    name: 'Handwoven Cotton Saree',
    category: 'Textiles',
    image: 'https://images.pexels.com/photos/34131689/pexels-photo-34131689.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    price: 2400,
    suggestedPrice: 2650,
    status: 'listed',
    languages: ['English', 'Hindi'],
    markets: 2,
    views: 186,
    createdAt: '2026-08-30',
  },
  {
    id: 'p4',
    name: 'Decorative Ceramic Plate',
    category: 'Pottery',
    image: 'https://images.pexels.com/photos/18646111/pexels-photo-18646111.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    price: 680,
    suggestedPrice: 750,
    status: 'draft',
    languages: ['English'],
    markets: 0,
    views: 0,
    createdAt: '2026-09-01',
  },
  {
    id: 'p5',
    name: 'Gemstone Gold Ring',
    category: 'Jewellery',
    image: 'https://images.pexels.com/photos/32382389/pexels-photo-32382389.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    price: 3200,
    suggestedPrice: 3500,
    status: 'published',
    languages: ['English', 'Hindi', 'Marathi', 'Kannada'],
    markets: 7,
    views: 689,
    createdAt: '2026-08-20',
  },
  {
    id: 'p6',
    name: 'Geometric Pattern Rug',
    category: 'Home Decor',
    image: 'https://images.pexels.com/photos/31854096/pexels-photo-31854096.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    price: 4500,
    suggestedPrice: 4800,
    status: 'listed',
    languages: ['English', 'Hindi', 'Gujarati'],
    markets: 4,
    views: 321,
    createdAt: '2026-08-27',
  },
];

export const sampleInsight: ProductInsight = {
  suggestedName: 'Hand-painted Blue Ceramic Vase',
  category: 'Pottery & Ceramics',
  description: 'A beautifully handcrafted ceramic vase featuring traditional blue pottery designs from Khurja. Each piece is individually shaped, painted, and glazed by skilled artisans, making every vase unique. The intricate floral patterns reflect the rich heritage of Indian pottery.',
  materials: 'Natural terracotta clay, lead-free blue glaze, mineral pigments',
  dimensions: 'Height: 25 cm, Diameter: 12 cm, Weight: 850 g',
  suggestedPrice: 1450,
  priceRange: { min: 1200, max: 1800 },
  marketDemand: 'high',
  demandTrend: 'rising',
  similarProducts: 142,
  competitorPrice: 1350,
  languages: ['English', 'Hindi', 'Bengali', 'Tamil', 'Telugu'],
  tags: ['Handmade', 'Blue Pottery', 'Home Decor', 'Traditional', 'Eco-friendly'],
  qualityScore: 87,
  improvementTips: [
    'Add 2-3 more photos from different angles to increase buyer trust',
    'Mention the artisan story — buyers pay 15-20% more for authentic crafts',
    'Include a size reference (coin or hand) in at least one photo',
  ],
};

export const bids: Bid[] = [
  {
    id: 'b1',
    productName: 'Hand-painted Blue Ceramic Vase',
    productImage: 'https://images.pexels.com/photos/18646120/pexels-photo-18646120.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    artisan: 'Ramesh Kumar',
    craft: 'Blue Pottery',
    basePrice: 1200,
    currentBid: 1450,
    bids: 7,
    location: 'Khurja',
    state: 'Uttar Pradesh',
    timeLeft: '2h 15m',
    status: 'active',
  },
  {
    id: 'b2',
    productName: 'Traditional Brass Earrings',
    productImage: 'https://images.pexels.com/photos/15955332/pexels-photo-15955332.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    artisan: 'Lakshmi Devi',
    craft: 'Brass Jewellery',
    basePrice: 850,
    currentBid: 920,
    bids: 4,
    location: 'Moradabad',
    state: 'Uttar Pradesh',
    timeLeft: '5h 40m',
    status: 'active',
  },
  {
    id: 'b3',
    productName: 'Handwoven Cotton Saree',
    productImage: 'https://images.pexels.com/photos/34131689/pexels-photo-34131689.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    artisan: 'Sita Bai',
    craft: 'Handloom Weaving',
    basePrice: 2400,
    currentBid: 2600,
    bids: 9,
    location: 'Chanderi',
    state: 'Madhya Pradesh',
    timeLeft: '45m',
    status: 'closing',
  },
  {
    id: 'b4',
    productName: 'Geometric Pattern Rug',
    productImage: 'https://images.pexels.com/photos/31854096/pexels-photo-31854096.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    artisan: 'Abdul Khan',
    craft: 'Carpet Weaving',
    basePrice: 4500,
    currentBid: 4800,
    bids: 6,
    location: 'Bhadohi',
    state: 'Uttar Pradesh',
    timeLeft: '8h 20m',
    status: 'active',
  },
  {
    id: 'b5',
    productName: 'Gemstone Gold Ring',
    productImage: 'https://images.pexels.com/photos/32382389/pexels-photo-32382389.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    artisan: 'Vikram Singh',
    craft: 'Jewellery Making',
    basePrice: 3200,
    currentBid: 3500,
    bids: 12,
    location: 'Jaipur',
    state: 'Rajasthan',
    timeLeft: '3h 10m',
    status: 'active',
  },
  {
    id: 'b6',
    productName: 'Decorative Ceramic Plate Set',
    productImage: 'https://images.pexels.com/photos/18646111/pexels-photo-18646111.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    artisan: 'Meena Patel',
    craft: 'Pottery',
    basePrice: 1500,
    currentBid: 1500,
    bids: 2,
    location: 'Khurja',
    state: 'Uttar Pradesh',
    timeLeft: '12h 5m',
    status: 'active',
  },
];

export const initialChatMessages: ChatMessage[] = [
  {
    id: 'c1',
    sender: 'ai',
    text: `Namaste Ramesh ji! I'm your AI Business Manager. I can help you with pricing, finding buyers, creating product listings, and answering questions about your craft business. What would you like to do today?`,
    time: 'Just now',
  },
];

export const aiSuggestions: string[] = [
  'What price should I set for my new vase?',
  'Find buyers for my pottery in Delhi',
  'Help me write a product description',
  'Which markets are best for brass items?',
];
